OPENAI_API_KEY="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"
NEWS_API_KEY="632dc651639546a2952dad139145003b"